import{S as w,i as v}from"./assets/vendor-Dg3uDB0e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function a(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function u(t){if(t.ep)return;t.ep=!0;const n=a(t);fetch(t.href,n)}})();const E="47437429-8394b140d2acf6ca490e5d99d",b="https://pixabay.com/api/";async function p(r){const e=`${b}?key=${E}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true`,a=await fetch(e);if(!a.ok)throw new Error("Failed to fetch images");return a.json()}const f=document.getElementById("gallery"),h=document.getElementById("loading");let d;function m(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}function y(r){f.innerHTML=r.map(e=>`
    <li>
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p><span>Likes:</span> <span class="value">${e.likes}</span></p>
          <p><span>Views:</span> <span class="value">${e.views}</span></p>
          <p><span>Comments:</span> <span class="value">${e.comments}</span></p>
          <p><span>Downloads:</span> <span class="value">${e.downloads}</span></p>
        </div>
      </a>
    </li>
  `).join(""),d?d.refresh():d=new w("#gallery a")}function s(r){v.error({title:"Error",message:r})}function I(){f.innerHTML=""}const $=document.getElementById("search-form"),P=document.getElementById("search-input"),o=document.createElement("button");o.textContent="Load more";o.classList.add("hidden","load-more");document.querySelector(".container").appendChild(o);let c=1;const L=15;let i="";$.addEventListener("submit",async r=>{if(r.preventDefault(),i=P.value.trim(),!i){s("Please enter a search term.");return}I(),c=1,m();try{const e=await p(i,c,L);e.hits.length===0?s("Sorry, there are no images matching your search query. Please try again!"):(y(e.hits),o.classList.remove("hidden"))}catch{s("An error occurred while fetching images.")}finally{g()}});o.addEventListener("click",async()=>{c+=1,m();try{const r=await p(i,c,L);r.hits.length===0?(o.classList.add("hidden"),s("We're sorry, but you've reached the end of search results.")):(y(r.hits),B())}catch{s("An error occurred while fetching more images.")}finally{g()}});function B(){const r=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
